### ISSUE TITLE
Get OTP enabled even if all numbers are not input

### ISSUE THREAD

**Issue by Rishabh510** [devfolioco/react-otp-input#49] opened 2019-10-03 18:56 UTC
- **Steps to reproduce the issue**:
In the demo site, when isInputNum is true, clicking either of the arrows enables the Get OTP button.

- **Relevant error messages and/or screenshots**:
**Before** clicking arrow
![image](https://user-images.githubusercontent.com/42823059/66155246-d2c40a00-e63c-11e9-83bf-3ae97e857a93.png)
**After** clicking arrow, the Get OTP button gets enabled.
![image](https://user-images.githubusercontent.com/42823059/66155374-1d458680-e63d-11e9-8ac3-1a8c2bcbc923.png)

**Comment by Rishabh510** [comment] 2019-10-03 19:08
Get OTP gets enabled even if you enter a single number.
![image](https://user-images.githubusercontent.com/42823059/66156423-3fd89f00-e63f-11e9-9990-64163eabc8bb.png)

**Comment by Gilbishkosma** [comment] 2019-10-04 04:15
@apollonian , i will work on this issue.

**Comment by apollonian** [comment] 2019-10-04 06:50
Sure, @Gilbishkosma!

**Comment by Snaked06** [comment] 2019-10-06 18:56
If you would allow @apollonian @Gilbishkosma i would love to work on this issue

**Comment by apollonian** [comment] 2020-07-04 11:32
The issue is now fixed with #73. Thank you for bringing it to notice @Rishabh510.

**Closed by apollonian** 2020-07-04 11:32 UTC
