### ISSUE TITLE
Bug Report: Not able to edit the otp

### ISSUE THREAD

**Issue by jaykay12** [devfolioco/react-otp-input#205] opened 2020-10-03 20:31 UTC
I am not sure whether this is intended functionality or a bug, but would like to bring into the notice.

### OTP Added
![Screenshot from 2020-10-04 01-54-50](https://user-images.githubusercontent.com/13948542/95001179-2cab3700-05e5-11eb-911f-f4cc4325028b.png)

### OTP is editable on first click inside textbox, as the text is getting selected
![Screenshot from 2020-10-04 01-55-08](https://user-images.githubusercontent.com/13948542/95001178-2c12a080-05e5-11eb-99ba-830b36c9d234.png)

### OTP is not editable once i reclick inside the textbox
![Screenshot from 2020-10-04 01-55-17](https://user-images.githubusercontent.com/13948542/95001177-2ae17380-05e5-11eb-92cd-667cb702f37a.png)

If this is a relevant issue, kindly approve & assign this to me.

**Comment by prateek3255** [comment] 2023-03-25 15:35
Duplicate of #356

**Closed by prateek3255** 2023-03-25 15:35 UTC
