### ISSUE TITLE
onKeyPress or onKeyDown feature is not available . 

### ISSUE THREAD

**Issue by Geetendra1** [devfolioco/react-otp-input#266] opened 2020-12-29 13:00 UTC
- **Describe the Feature Request**
I did not see any doc related to onKeyPress  or what so ever . please mention it here if available or add it if possible . 
- **Describe Preferred Solution**

**Comment by rajeshindium** [comment] 2021-11-29 08:48
when can I accept this feature

**Comment by shahid7292** [comment] 2021-12-29 06:51
Anything on this feature

**Comment by patilniranjan7** [comment] 2022-01-10 10:40
I need same for capture On Press Enter

**Comment by ritikbanger** [comment] 2022-08-09 17:24
The feature is available in: https://www.npmjs.com/package/react18-input-otp

**Comment by prateek3255** [comment] 2023-03-25 15:31
Duplicate of #352

**Closed by prateek3255** 2023-03-25 15:31 UTC
